name: Instafel APK Patcher

on:
  workflow_dispatch:
    inputs:
      instagram_apk_url:
        description: 'Instagram Alpha APK/AAB Download URL'
        required: true
        type: string
      apk_version:
        description: 'APK Version (for naming)'
        required: true
        type: string
        default: 'latest'

jobs:
  patch-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Instafel Repository
      uses: actions/checkout@v4
      with:
        repository: mamiiblt/instafel
        path: instafel
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
    
    - name: Install APK Tools & Bundle Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y apktool aapt zipalign
        
        # Download and install apksigner
        wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar
        chmod +x uber-apk-signer-1.3.0.jar
        sudo mv uber-apk-signer-1.3.0.jar /usr/local/bin/uber-apk-signer.jar
        
        # Download bundletool for converting AAB to APK
        wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
        chmod +x bundletool-all-1.15.6.jar
        sudo mv bundletool-all-1.15.6.jar /usr/local/bin/bundletool.jar
    
    - name: Download Instagram Bundle/APK
      run: |
        echo "Downloading Instagram file..."
        wget -O instagram-file "${{ github.event.inputs.instagram_apk_url }}"
        
        # Check if it's an AAB or APK
        file_type=$(file instagram-file)
        echo "File type: $file_type"
        
        if [[ $file_type == *"Zip archive"* ]] || [[ $file_type == *"Android"* ]]; then
          if [[ "${{ github.event.inputs.instagram_apk_url }}" == *".aab"* ]] || [[ $file_type == *"Android App Bundle"* ]]; then
            echo "Detected Android App Bundle (AAB)"
            mv instagram-file instagram-alpha.aab
            echo "BUNDLE_TYPE=aab" >> $GITHUB_ENV
          else
            echo "Detected APK"
            mv instagram-file instagram-alpha.apk
            echo "BUNDLE_TYPE=apk" >> $GITHUB_ENV
          fi
        else
          echo "Unknown file type, assuming APK"
          mv instagram-file instagram-alpha.apk
          echo "BUNDLE_TYPE=apk" >> $GITHUB_ENV
        fi
        
        ls -la instagram-alpha.*
    
    - name: Setup Gradle
      run: |
        cd instafel
        chmod +x gradlew
        ./gradlew --version
    
    - name: Build Instafel Patcher
      run: |
        cd instafel
        ./gradlew build
        
        # Find the built patcher JAR
        find . -name "*.jar" -type f | grep -E "(patcher|instafel)" | head -5
    
    - name: Convert Bundle to APK (if needed) and Patch
      run: |
        # Create working directory
        mkdir -p workspace
        cd workspace
        
        if [[ "$BUNDLE_TYPE" == "aab" ]]; then
          echo "Converting AAB to APK..."
          cp ../instagram-alpha.aab ./
          
          # Convert AAB to APKs using bundletool
          java -jar /usr/local/bin/bundletool.jar build-apks --bundle=instagram-alpha.aab --output=instagram-alpha.apks --mode=universal
          
          # Extract the universal APK
          unzip instagram-alpha.apks
          cp universal.apk instagram-alpha.apk
          
          echo "Conversion completed. APK size:"
          ls -lh instagram-alpha.apk
        else
          echo "Using provided APK..."
          cp ../instagram-alpha.apk ./
        fi
        
        # Decompile APK
        echo "Decompiling APK..."
        apktool d instagram-alpha.apk -o instagram-decompiled
        
        # This is where the Instafel injection would happen
        # The exact process depends on how Instafel's patcher works
        # You might need to:
        # 1. Copy Instafel's modified files to the decompiled APK
        # 2. Modify manifest and other configuration files
        # 3. Add Instafel's resources and assets
        
        echo "Patching process would happen here..."
        echo "This step needs to be customized based on Instafel's specific patching logic"
        
        # For now, we'll just recompile the APK as-is
        # In a real implementation, you'd inject Instafel's modifications here
        
        # Recompile APK
        echo "Recompiling APK..."
        apktool b instagram-decompiled -o instagram-patched-unsigned.apk
    
    - name: Sign APK
      run: |
        cd workspace
        
        # Generate a keystore for signing (for demo purposes)
        keytool -genkey -v -keystore release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=Developer, OU=Development, O=Company, L=City, S=State, C=US"
        
        # Sign the APK
        java -jar /usr/local/bin/uber-apk-signer.jar --apks instagram-patched-unsigned.apk --ks release-key.keystore --ksAlias alias_name --ksPass password --keyPass password
        
        # Rename the signed APK
        mv instagram-patched-unsigned-aligned-debugSigned.apk instagram-instafel-${{ github.event.inputs.apk_version }}.apk
    
    - name: Upload Patched APK
      uses: actions/upload-artifact@v4
      with:
        name: instafel-patched-apk-${{ github.event.inputs.apk_version }}
        path: workspace/instagram-instafel-${{ github.event.inputs.apk_version }}.apk
        retention-days: 30
    
    - name: Create Release (Optional)
      if: github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: patched-${{ github.event.inputs.apk_version }}
        release_name: Instafel Patched Instagram ${{ github.event.inputs.apk_version }}
        body: |
          🚀 **Patched Instagram APK with Instafel**
          
          - Version: ${{ github.event.inputs.apk_version }}
          - Built: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          
          ⚠️ **Important Notes:**
          - This is a modified version of Instagram
          - Use at your own risk
          - May violate Instagram's Terms of Service
          - Not affiliated with Meta/Instagram
          
          📱 **Installation:**
          1. Enable "Unknown Sources" in Android settings
          2. Download the APK from artifacts
          3. Install on your device
        draft: false
        prerelease: true
